version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio-compose-node-js
    ports:
      - "9000:9000"
      - "9001:9001"  # MinIO Console
    volumes:
      - /mnt/disk1:/mnt/disk1
      - /mnt/disk2:/mnt/disk2
      - /mnt/disk3:/mnt/disk3
      - /mnt/disk4:/mnt/disk4
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadminpassword"
    command: server /mnt/disk{1...4} --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  webhook:
    build: ./webhook
    ports:
      - "5000:5000"
    depends_on:
      - minio
    environment:
      - FLASK_ENV=development

volumes:
  minio-data:
